apiVersion: v1
kind: Service
metadata:
  name: scrapingnewsgo-service
  namespace: test
spec:
  selector:
    app: scrapingnewsgo
  ports:
    - protocol: TCP
      port: 30200
      targetPort: 30200
      nodePort: 30200
  type: NodePort
